from __future__ import annotations
from typing import Protocol, Sequence

class StudentsView(Protocol):
    def show_students(self, rows: Sequence[dict]) -> None: ...
    def get_student_form_data(self) -> dict: ...
    def get_selected_student_id(self) -> int | None: ...
    def clear_student_form(self) -> None: ...
    def show_message(self, text: str, level: str = "info") -> None: ...
    def confirm(self, text: str) -> bool: ...

class SubjectsView(Protocol):
    def show_subjects(self, rows: Sequence[dict]) -> None: ...
    def get_subject_form_data(self) -> dict: ...
    def get_selected_subject_id(self) -> int | None: ...
    def clear_subject_form(self) -> None: ...
    def show_message(self, text: str, level: str = "info") -> None: ...
    def confirm(self, text: str) -> bool: ...

class GradesView(Protocol):
    def show_grades(self, rows: Sequence[dict]) -> None: ...
    def get_grade_form_data(self) -> dict: ...
    def get_selected_grade_id(self) -> int | None: ...
    def clear_grade_form(self) -> None: ...
    def show_message(self, text: str, level: str = "info") -> None: ...
    def confirm(self, text: str) -> bool: ...
